service: chatter-backend
image: bdeak4/chatter-backend

registry:
  server: ghcr.io
  username: bdeak4
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  multiarch: false

env:
  clear:
    LOG_QUERY_THRESHOLD_MS: 500
  secret:
    - DATABASE_URL

audit_broadcast_cmd: ../infrastructure/scripts/audit-broadcast.sh

accessories:
  promtail:
    image: grafana/promtail:latest
    roles:
      - web
    cmd: |
      -config.file=/etc/promtail/config.yml \
      -config.expand-env=true
    env:
      clear:
        LOKI_HOST: logs-prod-012.grafana.net
      secret:
        - LOKI_USERNAME
        - LOKI_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    files:
      - ./config/promtail.yaml:/etc/promtail/config.yaml

traefik:
  args:
    accesslog: true
    accesslog.format: json
    accesslog.fields.headers.defaultmode: keep
    accesslog.fields.headers.names.Authorization: drop
    accesslog.fields.headers.names.Cookie: drop
    metrics.prometheus: true
    api.dashboard: true
  options:
    publish:
      - 8080:8080
  labels:
    traefik.http.routers.dashboard.entrypoints: traefik
    traefik.http.routers.dashboard.rule: PathPrefix(`/api`, `/dashboard`)
    traefik.http.routers.dashboard.service: api@internal
    traefik.http.routers.dashboard.middlewares: auth
    traefik.http.middlewares.auth.basicauth.users: admin:$apr1$Uwv/xaLq$cOQR/Hla.bxBKlmfICqEh/

healthcheck:
  path: /trpc/maintenance.healthz
  port: 4001

audit_broadcast_cmd: ../infrastructure/scripts/audit-broadcast.sh
