service: chatter-backend
image: bdeak4/chatter-backend

registry:
  server: ghcr.io
  username: bdeak4
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  multiarch: false

env:
  clear:
    LOG_QUERY_THRESHOLD_MS: 500
  secret:
    - DATABASE_URL

audit_broadcast_cmd: ../infrastructure/scripts/audit-broadcast.sh

accessories:
  promtail:
    image: grafana/promtail
    roles:
      - web
    cmd: -config.file=/etc/promtail/config.yaml -config.expand-env=true
    env:
      clear:
        LOKI_HOST: logs-prod-012.grafana.net
      secret:
        - LOKI_USERNAME
        - LOKI_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    files:
      - ./config/promtail.yaml:/etc/promtail/config.yaml

traefik:
  args:
    accesslog: true
    accesslog.format: json

healthcheck:
  path: /trpc/maintenance.healthz
  port: 4001
