auth_enabled: false # check this out

server:
  http_listen_port: 3100

ingester:
  chunk_idle_period: 3m
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-11-13
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        period: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  shared_store: aws

storage_config:
  aws:
    endpoint: ${LOGS_S3_ENDPOINT}
    bucketnames: ${LOGS_S3_BUCKET}
    access_key_id: ${LOGS_AWS_ACCESS_KEY_ID}
    secret_access_key: ${LOGS_AWS_ACCESS_KEY}
    region: ${LOGS_AWS_REGION}
    insecure: false
    sse_encryption: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: false
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /data/loki/index
    shared_store: s3
    cache_location: /data/loki/boltdb-cache

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

analytics:
  reporting_enabled: false
