global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: grafana
    static_configs:
      - targets:
          - grafana.chatter.exposed

  - job_name: loki
    static_configs:
      - targets:
          - loki.chatter.exposed

  - job_name: traefik
    static_configs:
      - targets:
          - 128.140.49.57:8080
          - 23.88.42.29:8080
          - 168.119.255.169:8080

  - job_name: node
    static_configs:
      - targets:
          - 128.140.49.57:9100
          - 23.88.42.29:9100
          - 168.119.255.169:9100

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://prometheus.io
          - https://dump.hr
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 23.88.42.29:9115
