creation_rules:
  - path_regex: dev\.enc
    age: >-
      age1mmc0rf8n6km2a5mygd457czjw9uf5t4x58yfflkta346zpylkupsjzydpn

  - path_regex: prod\.enc
    age: >-
      age1mmc0rf8n6km2a5mygd457czjw9uf5t4x58yfflkta346zpylkupsjzydpn

# bartol      mmc..dpn
