version: "3"

services:
  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: chatter
      POSTGRES_USER: chatter
      POSTGRES_PASSWORD: chatter
    ports:
      - 5001:5432

  cache:
    image: redis:6
    restart: on-failure
    ports:
      - 5002:6379

  web:
    build: .
    volumes:
      - .:/app
    restart: on-failure
    environment:
      FLASK_ENV: development
      POSTGRES_URL: "postgres://chatter:chatter@db:5432/chatter"
      REDIS_URL: "redis://redis:6379/"
    ports:
      - 4001:5000
    depends_on:
      - db
      - cache
