version: "3"

services:
  cache:
    image: redis:6
    restart: on-failure

  web:
    build: .
    volumes:
      - .:/app
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - cache
