name: E2E-testing
on: [push]
jobs:
  e2e:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: trpcdb
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: yarn/action-setup@v2.2.4
        with:
          version: 7.26.0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          # cache: 'yarn' # You can active this cache when your repo has a lockfile

      - name: Install deps (with cache)
        run: yarn install

      - name: Install playwright
        run: yarn playwright install chromium

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn-lock.yaml') }}-nextjs

      - name: Setup Prisma
        run: yarn prebuild

      - name: Build and test
        run: yarn build && yarn test-start && yarn test-dev

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            playwright/test-results
